parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: "module"
env:
  node: true
  es6: true
plugins:
  - '@typescript-eslint'
extends:
  - 'plugin:prettier/recommended'
rules:
  '@typescript-eslint/no-explicit-any':
    - error
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 80
      trailingComma: all
      tabWidth: 2
      arrowParens: avoid
